name: Build macOS Intel
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          brew install gtk4 libadwaita mpv gettext pkg-config

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

      - name: Build
        run: |
          export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig:/usr/local/lib/pkgconfig"
          cargo build --release --target x86_64-apple-darwin

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tsukimi-macos-intel
          path: target/x86_64-apple-darwin/release/tsukimi
