name: MacOS Intel Official 2026
on:
  workflow_dispatch:

jobs:
  build:
    # On utilise le nouveau label officiel pour Intel
    runs-on: macos-15-intel 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          # Ici, brew est déjà en mode Intel nativement !
          brew install gtk4 libadwaita mpv pkg-config dylibbundler gettext
          rustup target add x86_64-apple-darwin

      - name: Build Tsukimi
        run: |
          # Pas besoin de Rosetta, on compile normalement
          cargo build --release --locked --target x86_64-apple-darwin

      - name: Bundle App
        run: |
          mkdir -p Tsukimi.app/Contents/MacOS
          mkdir -p Tsukimi.app/Contents/Resources
          mkdir -p Tsukimi.app/Contents/Frameworks
          
          cp share/macos/Info.plist Tsukimi.app/Contents/
          cp share/macos/AppIcon.icns Tsukimi.app/Contents/Resources/
          cp target/x86_64-apple-darwin/release/tsukimi Tsukimi.app/Contents/MacOS/
          
          # Liaison des librairies
          dylibbundler -od -b \
            -x Tsukimi.app/Contents/MacOS/tsukimi \
            -d Tsukimi.app/Contents/Frameworks/ \
            -p @executable_path/../Frameworks/
          
          zip -r Tsukimi_Intel_Mac_Final.zip Tsukimi.app

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Tsukimi-Intel-Official
          path: Tsukimi_Intel_Mac_Final.zip
