name: Build Standalone macOS App
on: [push, workflow_dispatch]

jobs:
  bundle:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          brew install gtk4 libadwaita mpv gettext pkg-config dylibbundler

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

      - name: Install cargo-bundle
        run: cargo install cargo-bundle

      - name: Build and Bundle
        run: |
          export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig:/usr/local/lib/pkgconfig"
          # 1. On compile et on crée la structure .app
          cargo bundle --release --target x86_64-apple-darwin
          
          # 2. On crée le dossier pour les librairies à l'intérieur de l'app
          mkdir -p target/x86_64-apple-darwin/release/bundle/osx/Tsukimi.app/Contents/Frameworks
          
          # 3. On aspire les dépendances (GTK, MPV, etc.) dans l'app
          dylibbundler -od -b \
            -x target/x86_64-apple-darwin/release/bundle/osx/Tsukimi.app/Contents/MacOS/tsukimi \
            -d target/x86_64-apple-darwin/release/bundle/osx/Tsukimi.app/Contents/Frameworks/ \
            -p @executable_path/../Frameworks/

      - name: Compress App Bundle
        run: |
          cd target/x86_64-apple-darwin/release/bundle/osx/
          zip -r Tsukimi_Intel_Mac.zip Tsukimi.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tsukimi-Executable-Intel
          path: target/x86_64-apple-darwin/release/bundle/osx/Tsukimi_Intel_Mac.zip
